### ISSUE TITLE
sz/Practice05.hs error

### ISSUE THREAD

**Issue by marko1777** [AndrasKovacs/ELTE-func-lang#3]
State monad functor not properly implemented 
 `fmap f (State g) = State $ \s -> (f (fst $ g s), g s)`
there is a missing snd at the state, should be
`fmap f (State g) = State $ \s -> (f (fst $ g s), snd $ g s)`

Although it gets corrected at a later version! :)

**Comment by AndrasKovacs** [comment]
Feel free to PR.
